DROP TABLE users;
CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usrname text NOT NULL CHECK (usrname != ''), 
    pass text NOT NULL CHECK (pass != ''),
    name text NOT NULL CHECK (name != ''),
    gender CHAR(1) NOT NULL,
    age integer NOT NULL,
    phone BIGINT NOT NULL,
    birthdate date NOT NULL
);

DROP TABLE properties;
CREATE TABLE IF NOT EXISTS properties(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name != ''),
    description text NOT NULL,
    price DECIMAL NOT NULL,
    quantity integer NOT NULL
);

INSERT INTO users (usrname,pass,name,gender,age,phone,birthdate) values ('usuario1','1234','usuario1','F',20,6672096948,'11-08-1992');
INSERT INTO users (usrname,pass,name,gender,age,phone,birthdate) values ('usuario2','4567','usuario2','M',30,9871315678,'12-07-1993');
INSERT INTO users (usrname,pass,name,gender,age,phone,birthdate) values ('usuario3','9871','usuario3','F',47,1234567891,'13-06-1994');
insert into properties (name,description,price,quantity) values ('prop1','desc1',10.50,5);
insert into properties (name,description,price,quantity) values ('prop2','desc2',53.50,100);
insert into properties (name,description,price,quantity) values ('prop3','desc3',25.50,15);

select * from users;
select * from properties;


TRUNCATE TABLE users;
TRUNCATE TABLE properties; 